### ISSUE TITLE
Support for labels and comments

### ISSUE THREAD

**Issue by costezki** [citiususc/yatter#40]
It would be very useful to support `RDFS lexicalisation` or `SKOs lexicalisation`. 

We need to leave editorial comments and label mappings with references to "fields in a conceptual model". 
In RML/RDF is done like this:

```
tedm:AdditionalOrganisation a rr:TripleMap ;
    rr:subjectMap
        [
            rr:template "http://data.europa.eu/a4g/resource/AdditionalOrganisation/{replace(replace(/TED_EXPORT/CODED_DATA_SECTION/NOTICE_DATA/NO_DOC_OJS, ' ', '-' ), '/' , '-')}/{unparsed-text('https://digest-api.ted-data.eu/api/v1/hashing/fn/uuid/' || encode-for-uri(path()) || '?response_type=raw')}" ;
            rr:class org:Organization

        ] ;
    rml:logicalSource
    [
        rml:source "data/source.xml" ;
        rml:iterator "/TED_EXPORT/FORM_SECTION/F06_2014/CONTRACTING_BODY/ADDRESS_CONTRACTING_BODY_ADDITIONAL" ;
        rml:referenceFormulation ql:XPath
    ] ;
    rr:predicateObjectMap
        [
            rr:predicate epo:hasLegalName ;
            rr:objectMap
                [
                    rdfs:label "I.1.1	Official name	(BT-500	Organisation Name)" ;
                    rdfs:comment "This is a language dependent mapping. The way to access it is specific to each Form as it depends on the Root element." ;
                    rml:reference "OFFICIALNAME";
                    rml:languageMap [
                         rml:reference "lower-case(ancestor::F06_2014/@LG)"
                    ]
                ] ;
        ] .
```

**Comment by dachafra** [comment]
So, my suggestion for this would be something like (cc @anaigmo @andimou):
```
prefixes:
  foaf: http://xmlns.com/foaf/0.1/

mappings:
  AdditionalOrganisation:
    sources:
      - ['data.xml~XPath', '/Iterator']
    s: http://data.europa.eu/a4g/resource/AdditionalOrganisation/$(PATH_EXPRESION)
    po:
      - [epo:hasLegalName, $(OFFICIALNAME), $(lower-case(ancestor::F06_2014/@LG))~lang] # TITLE: I.1.1 [..] | COMMENT: This is a language [...]
```
