### ISSUE TITLE
Error when translating mapping file from YAML to RML

### ISSUE THREAD

**Issue by dgarijo** [citiususc/yatter#60]
**Describe the bug**
```
2023-05-04 19:08:11,348 | INFO: Translating YARRRML mapping to [R2]RML
2023-05-04 19:08:11,348 | ERROR: ERROR: The YARRRML mapping has not been translated
2023-05-04 19:08:11,349 | ERROR: can only concatenate str (not "list") to str
```

**To Reproduce**
`python3 -m yatter -i yarrrml_mappings_cf_2016_v2.yaml -o test.ttl`

**Expected behavior**
Mappings is translated into RML (it works with Matey)

YARRML file:
```
prefixes:
  ecfo: "https://w3id.org/ecfo#"
  qudt: "http://qudt.org/schema/qudt/"
  skos: "http://www.w3.org/2004/02/skos/core#"
  prov: "http://www.w3.org/ns/prov#"
  time: "http://www.w3.org/2006/time#"
  ecfo_instance: "https://w3id.org/ecfo/i/UK/BEIS/2016/"
  dc: "http://purl.org/dc/elements/1.1/"
  
sources:
  main-source: ['./data/conversion_factors_2016_modified.csv~csv']
mappings:
  CF:
    sources:
      - main-source

    s: ecfo_instance:CF_$(id)
    po:
      - [a, ecfo:EmissionConversionFactor]
      - [rdfs:description, $(Column Text)]
      - [ecfo:hasScope, https://w3id.org/ecfo#$(Scope)~iri]
      - [rdf:value, $(GHG Conversion Factor 2016),xsd:float]
      - [ecfo:hasTag, https://w3id.org/ecfo/i/$(Level 1)~iri]
      - [ecfo:hasTag, https://w3id.org/ecfo/i/$(Level 2)~iri]
      - [ecfo:hasTag, https://w3id.org/ecfo/i/$(Level 3)~iri]
      - [ecfo:hasTag, https://w3id.org/ecfo/i/$(Level 4)~iri]
      - [ecfo:sourceUnit, https://w3id.org/ecfo/i/$(UOM)~iri]
      - [ecfo:targetUnit, https://w3id.org/ecfo/i/$(GHG)~iri]
      - [ecfo:hasApplicablePeriod, ecfo_instance:applicablePeriod/$(valid_from)/$(valid_to)~iri]
      - [ecfo:hasApplicableLocation, http://www.wikidata.org/entity/Q145~iri]
      - [dc:publisher, https://w3id.org/ecfo/i/Organization/BEIS~iri]
      - [prov:wasDerivedFrom, https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/558103/2016_Flat_format_file_v01-01.xlsx, xsd:anyURI]
  
  Agent:
    sources:
       - main-source
     
    s: "https://w3id.org/ecfo/i/Organization/BEIS"
    po: 
      - [a, prov:Organization]
      - [rdfs:label, 'BEIS',xsd:string]

  TimeStart:
    sources:
        - main-source

    s: ecfo_instance:applicablePeriod/$(valid_from)/$(valid_to)/start
    po: 
      - [a, time:Instant]
      - [time:inXSDDate, $(valid_from),xsd:dateTime]

  TimeEnd:
      sources:
          - main-source
 
      s: ecfo_instance:applicablePeriod/$(valid_from)/$(valid_to)/end
      po: 
       - [a, time:Instant]
       - [time:inXSDDate, $(valid_to),xsd:dateTime ]
   
  TemporalEntity:
    sources:
        - main-source

    s: ecfo_instance:applicablePeriod/$(valid_from)/$(valid_to)
    po: 
     - [a, time:TemporalEntity]
     - [time:hasBeginning, ecfo_instance:applicablePeriod/$(valid_from)/$(valid_to)/start~iri]
     - [time:hasEnd, ecfo_instance:applicablePeriod/$(valid_from)/$(valid_to)/end~iri]

  L1:
    sources:
        - main-source
    s: https://w3id.org/ecfo/i/$(Level 1)
    po:
        - [a , skos:Concept]
        - [rdfs:label, $(Level 1)]

  L2:
    sources:
        - main-source
    s: https://w3id.org/ecfo/i/$(Level 2)
    po:
        - [a , skos:Concept]
        - [rdfs:label, $(Level 2)]

  L3:
    sources:
        - main-source
    s: https://w3id.org/ecfo/i/$(Level 3)
    po:
        - [a , skos:Concept]
        - [rdfs:label, $(Level 3)]

  L4:
    sources:
        - main-source
    s: https://w3id.org/ecfo/i/$(Level 4)
    po:
        - [a , skos:Concept]
        - [rdfs:label, $(Level 4)]

  sourceUnit:
    sources:
        - main-source
    s: https://w3id.org/ecfo/i/$(UOM)
    po:
        - [a , qudt:Unit]
        - [rdfs:label, $(UOM)]

  targetUnit:
    sources:
        - main-source
    s: https://w3id.org/ecfo/i/$(GHG)
    po:
        - [a , qudt:Unit]
        - [rdfs:label, $(GHG)]

```
