### ISSUE TITLE
Resolve prefixes in the generation of SubjectMap

### ISSUE THREAD

**Issue by marioscrock** [citiususc/yatter#68]
**Describe the bug**
Considering a SubjectMap `s: ex:person/$(firstname)` and a prefix `ex`, the prefix is not resolved when generating the SubjectMap.

**To Reproduce**
Use this mapping file
```
prefixes:
  ex: "http://example.com/"

mappings:
  person:
    sources:
      - ['persons.json~jsonpath', '$.persons[*]']
    s: ex:person/$(firstname)
    po:
      - [a, foaf:Person]
```

**Expected behavior**
In the SubjectMap generated the `ex:` is resolved as `http://example.com/`.
```
rr:subjectMap [
		a rr:SubjectMap;
		rr:template "http://example.com/person/{firstname}";
	];
```
