### ISSUE TITLE
yarrrml keyword graph is supported, but is not part of yarrrml spec

### ISSUE THREAD

**Issue by x-m-el** [citiususc/yatter#78]
**Describe the bug**
Given a yarrrml which includes a graph defined as `graph: https://example.com/$(id)`, yatter will convert this correctly, even though yarrrml does not support the keyword `graph`, instead `graphs` should be used (see https://rml.io/yarrrml/spec/#graphs)

**To Reproduce**
```
mappings:
  test:
    graph: https://example.com/$(id)
    s: https://example.com/$(id)
    po:
      - [a, ext:Test]
```
Will convert correctly to rml, even though `graph` is not a valid keyword.

**Additional context**
This is not a big problem, as still parsing correctly while containing a typo, can be seen as a feature.
It did cause confusion when using [morph_kgc](https://github.com/morph-kgc/morph-kgc), which had a different output for the given yarrrml (using `graph`) versus the converted rml file with yatter (which has correct syntax).
=> this might have been a fluke, but the comment still remains correct.
