### ISSUE TITLE
XLSX source is not supported

### ISSUE THREAD

**Issue by neobernad** [citiususc/yatter#79]
Hi @dachafra,

> Opening up a new issue as suggested in [#77](https://github.com/oeg-upm/yatter/issues/77#issuecomment-1963964367).

I have the following YARRRML file (actually it is longer and I have anonymized it):

```yaml
prefixes:
  ds_data: https://example.com/data/MyData/
  ds_property: https://example.com/MyProperty/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  grel: http://users.ugent.be/~bjdmeest/function/grel.ttl#
  morph-kgc: https://github.com/morph-kgc/morph-kgc/function/built-in.ttl#

sources:
  MyDataSource:
    - data.xlsx

mappings:
  PersonMappings:
    sources: MyDataSource

    s: ds_data:$(person_name)
    po:
      - [rdf:type, ds_property:Person]
      - [rdfs:label, $(person_name), xsd:string]

```

The execution of the translation of the file above raises an exception `ERROR: The YARRRML mapping has not been translated`:

```python
yaml = YAML(typ='safe', pure=True)
rml_content = yatter.translate(yaml.load(open("mappings.yml")))
```
Here, `rml_content` is `None`.

What could be wrong? After having a quick look debugging yatter, it seems that the YARRRML file is being properly opened and parsed, but something in the `translate` or `get_non_asserted_mappings` methods is not liking the structure of the mappings perhaps?

Thanks,
José Antonio

**Comment by dachafra** [comment]
Hi José Antonio,

Your mapping is missing the referenceFormulation, I understand that is CSV right?(https://rml.io/yarrrml/spec/#reference-formulation)

```
prefixes:
  ds_data: https://example.com/data/MyData/
  ds_property: https://example.com/MyProperty/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  grel: http://users.ugent.be/~bjdmeest/function/grel.ttl#
  morph-kgc: https://github.com/morph-kgc/morph-kgc/function/built-in.ttl#

sources:
  MyDataSource:
    - data.xlsx~csv

mappings:
  PersonMappings:
    sources: MyDataSource

    s: ds_data:$(person_name)
    po:
      - [rdf:type, ds_property:Person]
      - [rdfs:label, $(person_name), xsd:string]
```
