### ISSUE TITLE
SubjectMap templates with the word "type" in their name unable to translate

### ISSUE THREAD

**Issue by TheRazorace** [citiususc/yatter#87]
Error translating YARRRML mappings that contain the word "type" in a subject template. 

Example: 
````
sources:
  sem-table:
    access: 
      test.csv
    referenceFormulation: csv
    iterator: $

mappings:
  aircraft_typeTM:
    sources:
      - sem-table
    s: $(test_type)
    po:
      - p: a
        o: hhtp://example.com
````
