### ISSUE TITLE
Problem with translating references with parentheses to RML

### ISSUE THREAD

**Issue by TheRazorace** [citiususc/yatter#88]
References that contain parentheses are not translated correctly to RML. 

Example YARRRML mappings:

```
sources:
  table:
    access: 
      /Users/test.csv
    referenceFormulation: csv
    iterator: $

mappings:
  subjectTM:
    sources:
      - table
    s: $(Team)
    po:
      - p: http://www.wikidata.org/prop/direct/P2048
        o:
          - value: $(Payroll (millions))
            datatype: xsd:float
```

RML output:
```
<subjectTM_0> a rr:TriplesMap;

	rml:logicalSource [
		a rml:LogicalSource;
		rml:source "/Users/test.csv";
		rml:referenceFormulation ql:CSV;
		rml:iterator "$"
	];
	rr:subjectMap [
		a rr:SubjectMap;
		rml:reference "Team";
	];
	rr:predicateObjectMap [
		rr:predicateMap [
			a rr:PredicateMap;
			rr:constant <http://www.wikidata.org/prop/direct/P2048>;
		];
		rr:objectMap [
			a rr:ObjectMap;
			rml:reference "Payroll (millions";
			rr:datatype xsd:float
		];
	].
```
